replicaCount: 2

image:
  repository: 885412329878.dkr.ecr.us-east-1.amazonaws.com/payment-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: alb
  host: payment.example.com

serviceAccount:
  create: true
  name: payment-sa